### PR TITLE
Cool changes!

### PR DESCRIPTION
**Pull request by GamerPablito**
I made this as a little contribution to your engine bud.

This contains:
- Anti-aliasing option implanted to (almost) every sprite
- Added some functions that can come in handy to you in the `CoolUtil.hx` file
- Feature: Now it contains a GameJolt Adaptation, which can also be toggled in the `Project.xml` file, commenting the line: `GAMEJOLT_ALLOWED`

Hope this can be helpful for ya :)

### CODE REVIEW

**Comment by GamerPablito** [comment]
Seems like you won't need this after all :\

**Comment by polybiusproxy** [comment]
wait wait keep it open lmao

**Comment by polybiusproxy** [comment]
i'll merge it once im done with exams

**Comment by GamerPablito** [comment]
Oh ok

**Comment by GamerPablito** [comment]
But don't merge it yet!
I realized there are something that doesn't work correctly

**Comment by GamerPablito** [comment]
@polybiusproxy when you have the chance, go check the new PR #42 I made, cuz I made a mistake with the fork I created for this one

**Pull request closed without merging**
